### ISSUE TITLE
Failed to load ldlinux.c32?

### ISSUE THREAD

**Issue by prologic** [ivandavidov/minimal#10]
See screenshot: http://i.imgur.com/B0Y4OSM.png

Any ideas why a fresh build and bootup with qemu is failing with this message? (*I'll do some Googleing to see what I can find...*).

**Comment by therealprologic** [comment]
I think I just figured this out :)

See: https://github.com/mhiramat/boot2minc/blob/master/src/patches/kernel/x86-copy-linux-c32-for-newer.patch

I'm going ot try a newer kernel!

**Comment by ivandavidov** [comment]
I'm leaving this open, just in case. This shouldn't be a problem for most distros, if it is a problem at all.

**Comment by ivandavidov** [comment]
The experimental folder "musl-busybox" permanently fixes the issue.

**Comment by ivandavidov** [comment]
The experimental folder "glibc-busybox" also fixes this issue permanently. The DNS resolving issue is also fixed there.

**Comment by ivandavidov** [comment]
The latest published stable release '03-Apr-2016' fixes the problem and I'm closing the issue.
