### ISSUE TITLE
/usr merge

### ISSUE THREAD

**Issue by bauen1** [ivandavidov/minimal#108]
More specifically:
```
bin -> usr/bin
sbin -> usr/sbin
usr/sbin -> usr/bin
lib -> usr/lib
```

Since we are making breaking changes at the moment, I would like to hear your opinion on this.

**Comment by ivandavidov** [comment]
I assume you have in mind the overlay bundles. The only possible issue I see is the [library loading](https://linux.die.net/man/8/ld-linux) process.

_If a library dependency does not contain a slash, then it is searched for in the following order:
...
In the default path /lib, and then /usr/lib._

Right now ``/lib`` is reserved for GLIBC which comes as part of the MLL build process. I also use ``/usr/lib`` as workaround location to allow 32-bit libs to be 'visible' in 64-bit MLL [here](https://github.com/ivandavidov/minimal/blob/master/src/minimal_overlay/bundles/mll_utils/03_installer.sh#L124). However, these MLL utils are not really that useful and for now we can assume they will be dropped in the near future.

Another small issue might be the default ``$PATH`` but this can be easily fixed somewhere in the 'initramfs' execution chain.

Simply said, I see no problem to utilize ``/usr`` to its full potential

**Comment by ivandavidov** [comment]
``usr/sbin -> usr/bin``

Why would you want to do that?

**Comment by ivandavidov** [comment]
I'm closing this issue.
