### ISSUE TITLE
Implement switch which defines the build architecture

### ISSUE THREAD

**Issue by ivandavidov** [ivandavidov/minimal#113]
The idea is to have configurable switch which defines the targeted architecture. Right now the MLL build process relies on the default behavior of the build components (e.g. kernel, BusyBox, etc.) and by default these components are built for the same architecture as the host system.

In best case scenario there should be configurable switch with options for ``x86``, ``x86_64`` and ``auto`` (or no value, or if the option is commented). The ``auto`` option is equivalent of the current behavior and should be enabled by default.

**Comment by ivandavidov** [comment]
Some of the initial work has been done [here](https://github.com/ivandavidov/minimal/commit/f7c04f7a9faaa34bad06bc1399139b3f2322865c).

The kernel can be easily compiled for 32-bit x86 architecture by providing the ``ARCH`` property to 'make'.

``make ARCH=i386 defconfig``

GNU C library can be cross-compiled for 32-bit x86 architecture by providing few more properties to the ``./configure`` script.

```
./configure \
  --build=i686-linux \
  --host=i686-linux \
  --prefix= \
  --with-headers=$KERNEL_INSTALLED/include \
  --without-gd \
  --without-selinux \
  --disable-werror \
  CC="gcc -m32" \
  CXX="g++ -m32" \
  CFLAGS="$CFLAGS -march=i686" \ 
  CXXFLAGS="$CFLAGS -march=i686"
```

Some of the introduced properties may be redundant. Also, cross-compiling 'glibc' required the additional Debian/Ubuntu package ``gcc-multilib``.

However, cross-compiling BusyBox for 32-bit x86 architecture is quite troublesome. This needs further investigation.

**Comment by linus-ha** [comment]
Progress?

**Comment by ivandavidov** [comment]
MLL has been focused around x86_64 architecture for a long time, so this issue is no longer relevant. The original 32-bit support is still present in MLL but it's obsolete and perhaps it should be removed.

I'm closing the issue.
