### ISSUE TITLE
Split glibc_full into multiple bundles for each library

### ISSUE THREAD

**Issue by bauen1** [ivandavidov/minimal#114]
And add dependencies for each bundle that uses each library.
(Opening this as issue to hear your opinion on it)

**Comment by ivandavidov** [comment]
Do you mean one bundle for each library? This means there will be way too many libraries to handle. Nevertheless, it is good idea. And we can still have one meta-bundle which depends on all individual bundles.

**Comment by bauen1** [comment]
Implemented in #117
