### ISSUE TITLE
Use 'bash' as default script engine for all build operations

### ISSUE THREAD

**Issue by ivandavidov** [ivandavidov/minimal#122]
Recently the ``set -e`` 'bash' builtin has been introduced. Even though this may work with some other shell script engines, 'bash' is the industry standard for writing shell scripts. Moreover, using 'sh' instead of 'bash' may lead to some unexpected errors while building some of the overlay bundles. Note that in most Linux based operating systems the invocation of ``/bin/sh`` actually invokes 'bash' in compatibility mode.

All MLL build scripts, including the overlay bundle scripts, should be updated and the 'shebang' should point to ``/bin/bash``.

In addition, the ``apt`` dependencies list should be updated (e.g. in readme docs) and 'bash' should be added as mandatory dependency.

**Comment by bauen1** [comment]
POSIX.1-2008 requires sh to have support for fast-fail, so `set -e` is infact a `sh`-builtin.
http://pubs.opengroup.org/onlinepubs/9699919799/utilities/V3_chap02.html#tag_18

This would also require a bash bundle for self-hosting.

**Comment by ivandavidov** [comment]
Thank you, I didn't know that. I'll close the issue.
