### ISSUE TITLE
How install on HD?

### ISSUE THREAD

**Issue by HackerGaucho** [ivandavidov/minimal#14]
How install on HD using fdisk? It's possible create an extra sh file for it?

**Comment by ivandavidov** [comment]
Hello,

Currently I have no plans to support such feature. HD install is possible, since we talk about simple kernel + initramfs and this could be done with extlinux.

**Comment by HackerGaucho** [comment]
thx ivandavidov, and congratulations by your project

**Comment by ivandavidov** [comment]
The current development version of Minimal Linux Live supports both BIOS and UEFI boot modes. I have also implemented an installer which for now works in BIOS mode but I'll enhance it to work in UEFI mode as well.
