### ISSUE TITLE
Network Issue 

### ISSUE THREAD

**Issue by itsManjeet** [ivandavidov/minimal#144]
![image](https://user-images.githubusercontent.com/33650320/35469525-43b178b2-035c-11e8-876d-bbd5daca3be6.png)

Sir i found some issue in connecting to network 
on "ifconfig" it show on sit0 , lo
no eth0 found to connect 
i try all the minimal linux iso (2015-2018) and compile from source but same network issue in all

i am on ubuntu 17.10 (also on 17.04)
VirtualBox version 5.1.30

**Comment by TechnologyClassroom** [comment]
What are your network settings on the VM?  Did you include the OVERLAY_BUNDLES=dhcp line in the minimal/src/.config file when you compiled?  Do any other iso files get eth0 with the same virtualbox VM?

**Comment by ivandavidov** [comment]
This means that the kernel doesn't recognize the "eth0" network device. In VirtualBox you can try to change the network adapter, as suggested by @TechnologyClassroom.

Please have in mind that Minimal Linux Live is called "minimal" for a reason. It only includes the drivers that are enabled by default in the kernel configuration. Apparently, your VirtualBox setup uses network adapter which is not recognized by the MLL's kernel. On my VirtulaBox setup I'm using ``Intel PRO/1000 MT Desktop`` and it is recognized by MLL. You can try to update your configuration and use the same network adapter.
