### ISSUE TITLE
tar write error?

### ISSUE THREAD

**Issue by Zibri** [ivandavidov/minimal#154]
running ./build_minimal_linux_live.sh
downloads the kernel linux-4.14.12 then unpacks it and end by saying:
tar: write error

meh

**Comment by TechnologyClassroom** [comment]
What OS are you building from?  What is your version of tar?

**Comment by ivandavidov** [comment]
These are the general instructions from the front page of the project's website on how to proceed when the build result is "meh".

_"If your build fails for some reason, most probably there are unresolved build dependencies. Please have in mind that the build dependencies can vary a lot depending on the Linux OS that you use and the software that you have already installed. If you still have troubles, you should be able to identify the failing script from the console output. You may find it useful to enable "debug" logging in the failing shell script like this: set -ex. Manually run the failing script and identify the failing part. If you are unable to find a solution to your problem, then you can ask someone more experienced Linux guy around you or as alternative you can submit an issue."_

I suggest you take a look at the [Minimal Linux Script](https://github.com/ivandavidov/minimal-linux-script) project and try to build it step by step. This should give you enough knowledge and know-how on how to proceed with your local error.
