### ISSUE TITLE
Problems building kernels 4.15 and 4.16

### ISSUE THREAD

**Issue by ivandavidov** [ivandavidov/minimal#158]
All help on this issue is highly appreciated!

**4.16 (mainiline)** - missing ``bison`` dependency. There might be other errors later in the build chain 

**4.15.15 (stable)** - searching for ``<openssl/bio.h>`` and other ``openssl`` related header files, even though [kernel module signing](https://www.kernel.org/doc/html/v4.10/admin-guide/module-signing.html) is not selected. Installing the ``libssl-dev`` package should fix this issue. However, this option is not really an option since these headers should not be used at all.

**4.14.32 (longterm)** - no issues, as expected.

Figuring out the root cause of the issue for 4.15.x is top priority in order to move the project forward. Until then MLL is stuck to kernel version 4.14.x.

**Comment by AwlsomeAlex** [comment]
What is the environment which you build MLL? Mainly the distribution and I'll try to recreate it.

**Comment by ivandavidov** [comment]
I've been using ``Ubuntu 16.04`` as main host OS.

**Comment by ivandavidov** [comment]
More insight on the issue with kernel 4.15.

https://patchwork.kernel.org/patch/10172165/

**Comment by ivandavidov** [comment]
The issue has been fixed.

https://github.com/ivandavidov/minimal/commit/ee71569d870334913e7f942b2a37840ee16d4b4b
