### ISSUE TITLE
More required packages.

### ISSUE THREAD

**Issue by Sejoslaw** [ivandavidov/minimal#163]
Hey, I did try to compile the MLL but i needed few more packages than there are on main page of MLL:
bison and flex. I'm not sure if that is an issue.

**Comment by ivandavidov** [comment]
I suppose you've been looking at the dependencies that have been described in the website. The dependencies are for the latest released MLL version (back in January) and they are just fine. However, if you try to use newer kernel or glibc, then then you really need the additional dependencies that you mentioned. These dependencies have been handled in #158 and #160 and the corresponding dependency list has been updated in the project description. The dependency list in the website will be updated with the next MLL release (there is no planned date for that).

I'll close this issue, but feel free to raise other issues or comment on this one if you have any further notes.

**Comment by Sejoslaw** [comment]
Ok, thank You for Your answer :)
