### ISSUE TITLE
[Request / Idea] Add a .NET Core support.

### ISSUE THREAD

**Issue by Sejoslaw** [ivandavidov/minimal#164]
Hey I've been playing around with MLL and I totally love it <3
I have an idea that it could be awesome to add support for building .NET Core overlay bundle.
What do You think ?

**Comment by ivandavidov** [comment]
Yep, pretty much you'll need to have overlay bundle for each individual dependency, before we try to install .Net Core. And let's not forget that these dependencies might have other dependencies as well.

**Comment by Sejoslaw** [comment]
But still, it's doable xD

**Comment by SperoSophia** [comment]
Anyone looked at resolving the SCD dependencies for .NET on MLL
