### ISSUE TITLE
hdparm is missing support for ATA security functions

### ISSUE THREAD

**Issue by andriusst** [ivandavidov/minimal#165]
MLL includes hdparm but this one appears to be missing support for ATA security functions. For example switches such as "--security-set-pass" and "--security-erase" are not recognised. 

I've been using hdparm previously (under Gparted and CloneZilla live distros) and that supported the switches above.

How do I go about bringing the fully functional version of hdparm to MLL ? I am very new to linux but I installed Ubuntu and have built MLL using build scripts. Unfortunately hdparm still missing these functions. I guess build script does not take the pieces from the live system but downloads them instead...

**Comment by ivandavidov** [comment]
Hello,

Thank you for trying Minimal Linux Live!

MLL uses [BusyBox](https://busybox.net/downloads/BusyBox.html) as the provider for the main userland utility programs. The ``hdparm`` program is actually part of the BusyBox binary which includes many applet programs, one of which is ``hdparm``. You can find the supported options in the link if you search for the string 'hdparm'.

If you want to inclulde the full ``hdparm`` program in MLL you, I believe the easiest way to do that is to try the following procedure:

1. Under the folder **minimal_overlay/rootfs** create the folders **bin** and **lib64**.
2. Find the binary ``hdparm`` in your OS and copy it in the previously created folder **minimal_overlay/rootfs/bin**.
3. Open console and navigate to the folder **minimal_overlay/rootfs/bin**.
4. Execute the command ``ldd hdparm``. This should bring you list of all shared libraries (files ending with '.so') that have to be present in the MLL environment. If you get output that the hdparm binary is not a dynamically linked, then you don't need such libraries. Most probably the hdparm binary is dynamically linked and you will need these libraries.
5. Locate each individual library on your machine and copy it in the previously created folder **minimal_overlay/rootfs/lib64**.
6. Rebuld MLL.
7. Run MLL and try to use the command.

That should be enough but please have in mind that there might be other dependencies as well (e.g. configuration files or other libraries that are loaded at runtime which can't be detected by 'ldd'). Also, the libraries that you have identified, may have their dependencies as well and you have to provide these dependencies in MLL.

Let's hope that the 'hdparm' binary is simple enough and it is either statically compiled (therefore you'll need only the binary and no additional '.so' libraries), or it is simple dynamically linked binary and simple copy/paste of the libraries reported by 'ldd' should be enough to satisfy the dependencies.

Also, please have in mind that the 'hdparm' binary may have dependencies on the Linux kernel (no way to know that). By default MLL builds very simple kernel with default options. MLL doesn't add any modules or other kernel capabilities, apart from the default ones. This may or may not affect the behavior of 'hdparm' in the MLL environment.

I hope this explanation helps you!

Regards,
Ivan Davidov

**Comment by andriusst** [comment]
Thank you for such a quick response. Your explanations are very clear so I should be able to follow them easily. Will post back as soon as I get a chance to try this.

**Comment by ivandavidov** [comment]
You could use a faster procedure - do the same thing but instead of rebuilding and running MLL, you could remove/comment all overlay bundles that have been enabled by default (look in the ``.config`` file), then repackage MLL (there is a script for that purpose) and finally run MLL in Docker environment (there is script for that purpose as well).

This procedure could save you some time.
