### ISSUE TITLE
Integrate Travis-CI

### ISSUE THREAD

**Issue by ivandavidov** [ivandavidov/minimal#171]
As @ohmtech-rdi suggested, it's worth to utilize [Travis-CI](https://travis-ci.com/) in order to ensure that some (or perhaps all) of the MLL flavors are always stable. Currently the goal is to ensure that the supported firmware types can always be built. Second goal is to provide some kind of 'integration testing', either with ``Docker`` or by using some kind of automated QEMU environment.

**Comment by ivandavidov** [comment]
Travis CI doesn't support Ubuntu 18.04 natively. The latest supported Ubuntu version is 14.04 which is causing us many troubles. The Travis configuration should be updated and everything should happen in pulled Docker image with Ubuntu 18.04.

@ohmtech-rdi - can you take a look at this issue and perhaps implement proper Travis CI configuration which tests the firmware scenarios, as discussed in #170?

**Comment by ohmtech-rdi** [comment]
Travis-CI supports for 14.04 is a pain, and 16.04 support is into the making but for so long I don't know when it will come.

I remembered people using docker images instead for that reason, I guess this is what you refer to, but I have absolutely no experience in that. I guess that might be a lot of work, as this is the value that Travis-CI delivers in a nutshell, and what takes them so long with 16.04 apparently.

>  The latest supported Ubuntu version is 14.04 which is causing us many troubles

On the top of your head, do you remember what troubles you encountered?

If this is really impossible, my gut feeling would be for you to explore another CI system that would have support for more recent versions of Ubuntu. There is for example [Circle CI](https://circleci.com/) and apparently they have pre-configured [build environments](https://circleci.com/build-environments/#linux).

In [this article at the bottom of the page](https://blog.github.com/2017-11-07-github-welcomes-all-ci-tools/), you have a list of the ten top CI system used and integrated with GitHub.

I hope this will help.

**Comment by ivandavidov** [comment]
The first problem with Travis CI and their default 14.04 Ubuntu image was that the ``realpath`` binary was missing and when you install it, it is still very outdated. Also, GNU C Library refused to compile due to very old build toolchain.

Other limitations:
* MLL's build log is very long and Travis CI treats this as fatal error. I had to do some hacks in order to make the build log considerably smaller.
* As consequence, Travis CI failed because there were no log messages for more than 10 minutes. I had to implement custom _heartbeat_ asynchronous process which prints something in the log every 5 minutes.

I implemented some kind of final solution with Ubuntu 18.04 Docker image but this has some limitations as well. Even though the build process was OK, I wasn't able to test the generated MLL Docker image due to some strange error which is most probably related to the very old Docker version on the host system.

For now I'll leave the Travis CI configuration as it is. I might experiment with Docker in privileged mode and try to overcome the latest limitation by using Docker inside Docker but this is for another time.

**Comment by ohmtech-rdi** [comment]
> The first problem with Travis CI and their default 14.04 Ubuntu image was that the realpath binary was missing and when you install it, it is still very outdated. Also, GNU C Library refused to compile due to very old build toolchain.

That seems to indicate it's probably worth waiting for xenial or just take another build system. Travis is still the most popular, so maybe it's just that this is not ready for it. Too bad.

> MLL's build log is very long and Travis CI treats this as fatal error. I had to do some hacks in order to make the build log considerably smaller.

That's probably going to be the case for any CI system and IMHO a good limitation. I'm using google's [ninja](https://ninja-build.org) and it rewrites the last line apart from warnings and errors, which makes the log considerably smaller, but more importantly, way more readable and to the point.
In that case also there is no need for a heartbeat process.
I guess that using a "prettyfier" for `make` would be the way to go. Searched a bit but couldn't find one.

**Comment by ivandavidov** [comment]
I have implemented Docker test and QEMU test for Travis CI. Unfortunately, both tests don't work in Travis environment.

* Even though Docker's hello-world container works fine, it seems that adding new Docker images out of existing TGZ container layout causes troubles when we do that in second Docker process which runs in another 'privileged' Docker process. That's most probably due to the old Docker version in the old Ubuntu 14.04 environment.

* The QEMU test is tricky. The whole QEMU process is started as separate process. When MLL boots, new background process should be started. This background process is supposed to shutdown MLL after 60 seconds and as consequence the whole QEMU process should stop in graceful manner. Meanwhile, the main Travis CI process waits 2 minutes and checks if QEMU is still running. If it is running, then something is wrong. The problem is that the initramfs is not processed due to some weird QEMU issue and the QEMU process hangs there. After 2 minutes the Travis CI process detects that the QEMU process is still running and reports error. This QEMU issue might be due to the old Ubuntu 14.04 environment but I haven't researched it.

For now I have left only the basic build process as condition for correct execution. I will leave this issue open for a while if I somehow manage to fix the Docker/QEMU problems.

**Comment by TechnologyClassroom** [comment]
Gitlab.com has built-in CI.  I am curious how it would compare to Travis.
