### ISSUE TITLE
Quick question: Python interpreter not working

### ISSUE THREAD

**Issue by ghost** [ivandavidov/minimal#176]
Hi all! I tired to rebuild Minimal Linux in a more structured way and [this](https://github.com/alexanderthelegend/pylin) is the result. Now: The script compiles the Python binaries just fine, however when I try to run them on my minimal distro I get the following error:

```
/# python2
Could not find platform independent libraries <prefix>
Could not find platform dependent libraries <exec_prefix>
Consider setting $PYTHONHOME to <prefix>[:<exec_prefix>
Fatal Python error: Unable to get the locale encodings
ImportError: No module named 'encodings'
Aborted
# same for Python 3
```

What options do I have to pass to `configure` or `make` so that the Python interpreter springs up instead of these errors? Also any help on how I can add networking to my minimal distro would be great!  Much obliged already for making this great project!

**Comment by TechnologyClassroom** [comment]
Do you have your python scripts posted publicly?

**Comment by ivandavidov** [comment]
Long story short - when you build statically linked software, you have to provide all external dependencies as well.

When you generate statically linked binaries, even though the binary execution can be started without dependencies to OS libraries, there might be some external file/library dependencies.

``./configure LDFLAGS="-static" --disable-shared --prefix=/usr``

In this case I believe all such dependencies are located under ``/usr`` on the machine where you compiled Python. I suggest you do the following:

* Change the ``prefix`` to new, completely empty directory. Let's say the folder is ``/python``.
* Build Python as usual.
* Copy the ``/python`` folder in the initramfs structure under the same name and location.
* Copy the Python binary in the initramfs structure (exactly what you are doing now, no differences).

Note that this may not be enough to run Python. If you want statically linked Python in your OS, you have to provide all external file dependencies and there may be more dependencies which you'll have to track down.

One way to track these dependencies is by using ``strace`` inside your OS by executing ``strace python``. Of course, this means that you have to add ``strace`` in your OS, which most probably is not statically linked, which means you'll have to provide its dependencies as well. You can find the ``strace dependencies`` by executing ``ldd $(which strace)``.

**Comment by ivandavidov** [comment]
Regarding the networking - statically linked Busybox can't offer you DNS functionality. You can have IP networking but you simply can't have DNS functionality, at least not in easy way. Very old versions of MLL use statically linked Busybox and they have network support but without DNS. 

My suggestion is to focus on dynamically linked software, including dynamically linked Busybox, which in turn will require ``GLIBC``. I believe the ``03-Apr-2016`` version of MLL ([changelog](http://minimal.idzona.com/#changes)) is the best place to start with, if you decide to explore the dynamically linked approach of building Linux based OS.

**Comment by iamletigre** [comment]
@ivandavidov Hi, thanks I will look into it and if I have some questions just ask you here. I hope this is alright!😊
