### ISSUE TITLE
boot in vmware does not show disk

### ISSUE THREAD

**Issue by secmask** [ivandavidov/minimal#180]
I try to boot iso file in Vmware, but I can't see the HDD device in `/dev/sdXX`, 
sorry I dont know where to post the question.

**Comment by ivandavidov** [comment]
The MLL ISO image should be available under ``/dev/sr0``. Regarding all other devices, please have in mind that the Linux kernel in MLL is compiled with default options and the hardware detection is very limited. However, in virtualized environment (e.g. QEMU and VMware Player) the HDD devices should be detected without issues. If you have troubles with the HDD devices, try to change the HDD type. Once again, MLL is small and the impact of having small OS is that the hardware detection is quite limited.

Please let me know how it goes and if you still experience the issue.

Regards,
Ivan Davidov

**Comment by secmask** [comment]
I tried to change HDD:
- IDE -> no /sdx or /dev/hdx show up
- SCSI -> no /sdx , /dev/sdx show up
- SATA -> worked, /dev/sda appear

> the Linux kernel in MLL is compiled with default options and the hardware detection is very limited

could you suggest which module to enable to support other HDD type?

**Comment by ivandavidov** [comment]
Bad news - by default there are no kernel modules in MLL. Again, this is limitation of having very small OS.

MLL is mostly and educational tool to experiment with. If you want to have specific hardware support, you need to recompile the Linux kernel (see script "02") and explicitly build the modules that you want. Another option is to add the modules that you want as "overlay bundle" (see the "kernel_modules" overlay bundle). However, in both cases you need to play with the MLL build infrastructure and write the functionality that you want.

If you need quite minimal OS with more features, I suggest you take a look at [Slax](http://slax.org) or perhaps another small live OS.

**Comment by secmask** [comment]
ok, thank you @ivandavidov!
