### ISSUE TITLE
Add custom shell script / ncurses application

### ISSUE THREAD

**Issue by ipochi** [ivandavidov/minimal#181]
@ivandavidov 

I want to add a custom shell script or an ncurses application that interacts with the user 
after the livecd/liveusb of minimal_linux_live boots up.

Where would i make the modification to achieve the same ?

The requirement for me is that user will enter the live usb [created from custom minimal live iso]
Custom script or ncurses program loads up and asks the user for input.
User provides that and the script/program continues its thing depending on user's input.

Once script/program is completed, the user is asked for reboot.

I apologize if this is not the place to ask such a question.
I felt minimal_linux_live could be perfect for what I want.

I tried live_build from debian , created iso but I dont know how to add my custom program to run at boot.

**Comment by ipochi** [comment]
A follow up , 
I can add call to my custom program in the init script ?

**Comment by bauen1** [comment]
You would probably like to edit this file:
https://github.com/ivandavidov/minimal/blob/master/src/minimal_rootfs/etc/inittab
The syntax for the busybox inittab is described here:
https://git.busybox.net/busybox/tree/examples/inittab

In particular you probably want to replace
```bash
::once:cat /etc/motd
::respawn:/bin/cttyhack /bin/sh
```
with something like
```bash
::once:/usr/bin/my_script.sh
::respawn:/bin/cttyhack /bin/sh
```
This will keep your script running on ttty1/console and allow the user to switch to the other login shells. It will run your script once and then drop the user to a shell.

**Comment by ivandavidov** [comment]
@ipochi - this [README](https://github.com/ivandavidov/minimal/blob/master/src/README) document explains the procedure of adding more software in Minimal Linux Live.

Please have in mind that MLL is mostly an educational tool. MLL is not designed to run on real hardware (it is designed to run in virtual machines, e.g. QEMU, VMware Player, VirtualBox, etc.) and even if you install it on USB flash drive, the default hardware detection in MLL is very limited. Nevertheless, you can give it a try and see if works for you. I hope it does!

Regards,
Ivan Davidov

**Comment by ipochi** [comment]
@ivandavidov 

Thanks ,  Iwill go through the document.

My ideal scenario is to use Debian's live-build.
But I thought the idea of running my custom ncurses application during bootup should work out 
anywhere as long I understand the basics of where to make the changes.

I'll try the changes @bauen1 mentioned.

**Comment by ipochi** [comment]
> You would probably like to edit this file:
> https://github.com/ivandavidov/minimal/blob/master/src/minimal_rootfs/etc/inittab
> The syntax for the busybox inittab is described here:
> https://git.busybox.net/busybox/tree/examples/inittab
> 
> In particular you probably want to replace
> 
> ```shell
> ::once:cat /etc/motd
> ::respawn:/bin/cttyhack /bin/sh
> ```
> 
> with something like
> 
> ```shell
> ::once:/usr/bin/my_script.sh
> ::respawn:/bin/cttyhack /bin/sh
> ```
> 
> This will keep your script running on ttty1/console and allow the user to switch to the other login shells. It will run your script once and then drop the user to a shell.

@bauen1 
Would updating the inittab should work with live-build as well ?
