### ISSUE TITLE
how to install CLI linux on minimal linux?

### ISSUE THREAD

**Issue by osmand** [ivandavidov/minimal#182]
Hello Im not very experienced in linux

how would I install and run command line interface binary of php 5-7

minimal doesnt have ftp and I have little idea of how to install any of them

if I had ftp perhaps I could download it from somewhere and then extract and run it?

thanks.

**Comment by ivandavidov** [comment]
MLL is an educational operating system. You should examine MLL's internal structure, read all documentation documents and then experiment with MLL. After that you should have the necessary knowledge to add whatever you want.

**P.S.** Take a look at the overlay bundle structure and how the other programming languages have been added.
