### ISSUE TITLE
Unable to mount root fs on unknown-block

### ISSUE THREAD

**Issue by DHunte** [ivandavidov/minimal#186]
Hi,

I have been having issues with the build_minimal_linux_live.sh script with the iso it produces. With no modifications i cannot use the iso produced when loaded into virtual-box or made as a live-usb i only ever receive the error:

`end kernel panic - not syncing: VFS: Unable to mount root fs on unkown-block(0,0) ]`

**Comment by ivandavidov** [comment]
Please have in mind that we are talking about operating system which is a complex software. There could be many reasons why it doesn't work for you. How much RAM are you using? Were there any interim failures during the build process? Did you make any changes in MLL? Have you resolved all build dependencies?

You should build all MLL components one by one and examine the result. Finally, try to boot the ISO with QEMU by using the provided script. If it works with QEMU, it should also work with VirtualBox, unless there is a bug with VirtuslBox.
