### ISSUE TITLE
Boot MLL through PXE

### ISSUE THREAD

**Issue by oxedions** [ivandavidov/minimal#190]
Hello,

I am trying to load MLL through PXE (using an iPXE rom). In my field, we are always working with old kernels, and having the ability to load a very recent one for debug/tests purposes is very interesting. 

While I can get the kernel and it's rootfs working, I of course cannot get the overlay over bundles as no /dev/sd or /dev/sr device contains the iso I generated.

- Using sanboot, I just can't get access to iso.
- Using memdisk, I should be able to get access to iso, using specific kernel modules (https://wiki.syslinux.org/wiki/index.php?title=MEMDISK#Linux), but I need to add this into the compilation scripts.
- Last methods, which I would prefer, would be to have the possibility to pack all the bundles into the rootfs, and then start the overlay above this. However, I fail to do this due to the fact that I need too much space:

```
[root@241111cecf84 src]# ./13_prepare_iso.sh
*** PREPARE ISO BEGIN ***
Firmware type is 'both'.
Removing old ISO image work area. This may take a while.
Preparing new ISO image work area.
IMAGESIZE 13980530
Creating UEFI boot image file '/root/Minimal_Live_Linux/src/work/uefi.img'.
Attaching hard disk image file to loop device.
losetup: /root/Minimal_Live_Linux/src/work/uefi.img: Warning: file does not fit into a 512-byte sector; the end of the file will be ignored.
Formatting hard disk image with FAT filesystem.
mkfs.fat 4.1 (2017-01-24)
Preparing 'uefi' work area.
Preparing kernel and rootfs.
Preparing 'systemd-boot' UEFI boot loader.
Preparing 'systemd-boot' configuration.
cp: error writing '/root/Minimal_Live_Linux/src/work/uefi/loader/entries/mll-x86_64.conf': No space left on device
[root@241111cecf84 src]#
```

I could "cheat" and modify `image_size=$((kernel_size + rootfs_size + loader_size + 65536))` in 13_ script, but I am not sure.

What would be the best way to allow MLL to be used over PXE?

I think this could be a nice feature to be added to MLL :-)
I would be ready to develop it if you provide me guidance on what should be the best solution to you.

With my best regards

Ox

**Comment by ivandavidov** [comment]
Hi Ox,

I'm afraid I have no recommendation regarding MLL and PXE booting since this is quite an odd boot scenario and I never really thought about it (sorry...) . Nevertheless, this is really interesting and I am open for suggestions. I'll be happy if you could come up with proposal or with working solution.

**Comment by oxedions** [comment]
Hi,

Many thanks for the feedback :-)
I will try to find the best way to achieve that and keep you informed.

By the way, your stress bundle URL is down (404 error). Maybe this one can replace it?
https://fossies.org/linux/privat/stress-1.0.4.tar.gz

Ox

**Comment by TechnologyClassroom** [comment]
Slackbuilds says the md5sum for the package is a607afa695a511765b40993a64c6e2f4 and links to fedora hosting. https://slackbuilds.org/repository/14.2/system/stress/

https://src.fedoraproject.org/repo/pkgs/stress/stress-1.0.4.tar.gz/a607afa695a511765b40993a64c6e2f4/stress-1.0.4.tar.gz

**Comment by ivandavidov** [comment]
The stress bundle has been fixed (hopefully permanently). I'm closing this issue now. Any further discussions are welcome as new issues.
