### ISSUE TITLE
Regarding sysroot

### ISSUE THREAD

**Issue by moliata** [ivandavidov/minimal#195]
Hello,
Isn't `sysroot` used when you need to cross-compile? Why was it used here? Can't we just compile busybox (dynamically linked) without using `sysroot`?
Best regards,
Ben.

**Comment by ivandavidov** [comment]
We can compile Busybox without using the ``sysroot`` folder, but in this case, you'd be compiling with the host OS GNU C libraries/headers and with the host OS kernel headers. The ``sysroot`` folder contains the MLL specific kernel/glibc artifacts and after we have prepared it, we compile Busybox with these artifacts.

**Comment by moliata** [comment]
I see, thank you.

**Comment by moliata** [comment]
@ivandavidov it seems, that overlay bundles when compiling don't use the sysroot and compile against host OS glibc, right? Why don't you use sysroot with all bundles?

**Comment by ivandavidov** [comment]
The overlay bundles don't use the sysroot. That's because most overlay
bundle software don't support such option. You may be able to modify the
build process for few of the bundles and compile them with MLL's sysroot,
but this is big hack. Feel free to try it if you want.
