### ISSUE TITLE
Can't cook

### ISSUE THREAD

**Issue by MESWEB** [ivandavidov/minimal#198]
> linux-5.3.8/arch/x86/kernel/cpu/mtrr/cleanup.c
xz: (stdin): Compressed data is corrupt
linux-5.3.8/arch/x86/kernel/cpu/mtrr/cyrix.c
tar: Child returned status 1
tar: Error is not recoverable: exiting now

**Comment by ivandavidov** [comment]
I can't cook either. But my wife can.

Regarding your issue - start from scratch. Delete all sources and begin the build process from the very beginning.

**Comment by MESWEB** [comment]
Nope it's not a solution. When I swap kernel to 5.2.7 then everything work great. So it's mean 5.2.8 have a bug. Aha please add rsync install before making headers.
