### ISSUE TITLE
Run existing kernel source code 

### ISSUE THREAD

**Issue by cirosantilli** [ivandavidov/minimal#20]
Instead of downloading the kernel under work, I want to reuse an existing kernel source to help testing a hacked kernel for development.

I have implemented that at: https://github.com/cirosantilli/runlinux based on this repo. Feel free to link from the README to it if deemed worthy :-)

Also if you find it interesting, I can patch this repo to do that as well: we could add a `--src` flag that points to the desired source to use.

**Comment by ivandavidov** [comment]
Thanks for letting me know!

I'd like to keep my sources modular and easy to follow, so I'm afraid I won't adopt your proposal. More or less, the same effect can be simulated by *not* executing scripts 1 and 2 with few additional commands around. I see you've already implemented your scripts in similar fashion.

I like the idea, though and I'll put link to your project soon.
