### ISSUE TITLE
Minimal in musl/clang/llvm?

### ISSUE THREAD

**Issue by scsijon** [ivandavidov/minimal#201]
Question really, any thoughts of ccreating a musl/clang/llvm version?

**Comment by ivandavidov** [comment]
Short answer - no.

Long answer - if you are able to understand how MLL is built, you should also be able to create your own version of MLL with "musl" and/or other components. After all, MLL is mostly an educational tool.

**Comment by scsijon** [comment]
Ah, didn't pick that up, thank you for the reply, as I have a copy downloaded i might just take you up with that idea in the new year.
