### ISSUE TITLE
NTFS Filesystem Support

### ISSUE THREAD

**Issue by krahul24x7** [ivandavidov/minimal#203]
I am trying to mount ntfs partition, but I guess it does not support ntfs for now.
Please help me to know how can I use ntfs partition with this MLL.

Thanks

**Comment by ivandavidov** [comment]
Taken from the MLL website:

_The generated ISO image file contains Linux kernel, GNU C library compiled with default options, BusyBox compiled with default options, quite simple initramfs structure and some "overlay bundles" (the default build process provides few overlay bundles). You don't get Windows support out of the box, nor you get any fancy desktop environment. All you get is a simple shell console with default BusyBox applets, network support via DHCP and... well, that's all. This is why it's called "minimal"._

You need to do some research on the Linux filesystem support and how to enable different filesystems via kernel configurations. Hint - you'll need to rebuild MLL. Google is your best friend.
