### ISSUE TITLE
BusyBox 1.31.1 fails to build under glibc 2.31

### ISSUE THREAD

**Issue by AwlsomeAlex** [ivandavidov/minimal#205]
(Latest as of 2/7/2020)
**Linux Kernel:** 5.4.18
**GNU C Library:** 2.31
**BusyBox Userland:** 1.31.1

Long time no speak,
With the new glibc (2.31), there seems to be something wrong with the BusyBox (1.31.1) compile process for Minimal Linux Live. The inital output is: `Failed: -Wl,--start-group  -lcrypt -lm -lresolv  -Wl,--end-group`

Not sure if I should escalate this to a BusyBox problem, or if there's a compiler flag that needs to be changed. 

The whole output is:
`gcc -Wall -Wshadow -Wwrite-strings -Wundef -Wstrict-prototypes -Wunused -Wunused-parameter -Wunused-function -Wunused-value -Wmissing-prototypes -Wmissing-declarations -Wno-format-security -Wdeclaration-after-statement -Wold-style-definition -fno-builtin-strlen -finline-limit=0 -fomit-frame-pointer -ffunction-sections -fdata-sections -fno-guess-branch-probability -funsigned-char -static-libgcc -falign-functions=1 -falign-jumps=1 -falign-labels=1 -falign-loops=1 -fno-unwind-tables -fno-asynchronous-unwind-tables -fno-builtin-printf -Os -Os -s -fno-stack-protector -fomit-frame-pointer -U_FORTIFY_SOURCE -L/home/awlsomealex/Git/minimal/src/work/sysroot/lib --sysroot=/home/awlsomealex/Git/minimal/src/work/sysroot -o busybox_unstripped -Wl,--sort-common -Wl,--sort-section,alignment -Wl,--gc-sections -Wl,--start-group applets/built-in.o archival/lib.a archival/libarchive/lib.a console-tools/lib.a coreutils/lib.a coreutils/libcoreutils/lib.a debianutils/lib.a klibc-utils/lib.a e2fsprogs/lib.a editors/lib.a findutils/lib.a init/lib.a libbb/lib.a libpwdgrp/lib.a loginutils/lib.a mailutils/lib.a miscutils/lib.a modutils/lib.a networking/lib.a networking/libiproute/lib.a networking/udhcp/lib.a printutils/lib.a procps/lib.a runit/lib.a selinux/lib.a shell/lib.a sysklogd/lib.a util-linux/lib.a util-linux/volume_id/lib.a archival/built-in.o archival/libarchive/built-in.o console-tools/built-in.o coreutils/built-in.o coreutils/libcoreutils/built-in.o debianutils/built-in.o klibc-utils/built-in.o e2fsprogs/built-in.o editors/built-in.o findutils/built-in.o init/built-in.o libbb/built-in.o libpwdgrp/built-in.o loginutils/built-in.o mailutils/built-in.o miscutils/built-in.o modutils/built-in.o networking/built-in.o networking/libiproute/built-in.o networking/udhcp/built-in.o printutils/built-in.o procps/built-in.o runit/built-in.o selinux/built-in.o shell/built-in.o sysklogd/built-in.o util-linux/built-in.o util-linux/volume_id/built-in.o -Wl,--end-group -Wl,--start-group -lcrypt -lm -lresolv -Wl,--end-group`

`/usr/bin/ld: coreutils/lib.a(mktemp.o): in function `mktemp_main':
mktemp.c:(.text.mktemp_main+0x80): warning: the use of `mktemp' is dangerous, better use `mkstemp' or `mkdtemp'
/usr/bin/ld: util-linux/lib.a(rdate.o): in function `rdate_main':
rdate.c:(.text.rdate_main+0xe4): undefined reference to `stime'
/usr/bin/ld: coreutils/lib.a(date.o): in function `date_main':
date.c:(.text.date_main+0x218): undefined reference to `stime'
collect2: error: ld returned 1 exit status
Note: if build needs additional libraries, put them in CONFIG_EXTRA_LDLIBS.
Example: CONFIG_EXTRA_LDLIBS="pthread dl tirpc audit pam"
make[1]: [Makefile:718: busybox_unstripped] Error 1
make[1]: Leaving directory '/home/awlsomealex/Git/minimal/src/work/busybox/busybox-1.31.1'
Command exited with non-zero status 2`

**Comment by ivandavidov** [comment]
**GLIBC 2.31**

_The obsolete function ``stime`` is no longer available to newly linked binaries, and its declaration has been removed from <time.h>. Programs that set the system time should use clock_settime instead._

**Comment by ivandavidov** [comment]
It seems that the build process uses GLIBC headers from the host system (version < 2.31), while the actual binaries come from the newly downloaded GLIBC (version = 2.31).

**Comment by AwlsomeAlex** [comment]
I want to say that I've even had this problem with crossed complied GLIBC headers under 2.31.... but I don't remember how those tests went. I'll try again tonight.

**Comment by jiujiangxueyuan** [comment]
I met this problem too
![image](https://user-images.githubusercontent.com/35907685/111017849-b65efc00-83f0-11eb-83f1-f42eae67aeee.png)
and the GLIBC version is 2.32.

**Comment by hnxy7231** [comment]
> (ล่าสุดเมื่อ 2/7/2020)
> **Linux Kernel:** 5.4.18
> **GNU C Library:** 2.31
> **BusyBox Userland:** 1.31.1
> 
> ไม่ได้คุยกันนาน
> ด้วย glibc ใหม่ (2.31) ดูเหมือนว่าจะมีบางอย่างผิดปกติกับกระบวนการคอมไพล์ BusyBox (1.31.1) สำหรับ Minimal Linux Live เอาต์พุตเริ่มต้นคือ:`Failed: -Wl,--start-group -lcrypt -lm -lresolv -Wl,--end-group`
> 
> ไม่แน่ใจว่าฉันควรส่งต่อไปยังปัญหา BusyBox หรือไม่ หรือต้องมีการตั้งค่าสถานะคอมไพเลอร์ที่ต้องเปลี่ยน
> 
> The whole output is:
> `gcc -Wall -Wshadow -Wwrite-strings -Wundef -Wstrict-prototypes -Wunused -Wunused-parameter -Wunused-function -Wunused-value -Wmissing-prototypes -Wmissing-declarations -Wno-format-security -Wdeclaration-after-statement -Wold-style-definition -fno-builtin-strlen -finline-limit=0 -fomit-frame-pointer -ffunction-sections -fdata-sections -fno-guess-branch-probability -funsigned-char -static-libgcc -falign-functions=1 -falign-jumps=1 -falign-labels=1 -falign-loops=1 -fno-unwind-tables -fno-asynchronous-unwind-tables -fno-builtin-printf -Os -Os -s -fno-stack-protector -fomit-frame-pointer -U_FORTIFY_SOURCE -L/home/awlsomealex/Git/minimal/src/work/sysroot/lib --sysroot=/home/awlsomealex/Git/minimal/src/work/sysroot -o busybox_unstripped -Wl,--sort-common -Wl,--sort-section,alignment -Wl,--gc-sections -Wl,--start-group applets/built-in.o archival/lib.a archival/libarchive/lib.a console-tools/lib.a coreutils/lib.a coreutils/libcoreutils/lib.a debianutils/lib.a klibc-utils/lib.a e2fsprogs/lib.a editors/lib.a findutils/lib.a init/lib.a libbb/lib.a libpwdgrp/lib.a loginutils/lib.a mailutils/lib.a miscutils/lib.a modutils/lib.a networking/lib.a networking/libiproute/lib.a networking/udhcp/lib.a printutils/lib.a procps/lib.a runit/lib.a selinux/lib.a shell/lib.a sysklogd/lib.a util-linux/lib.a util-linux/volume_id/lib.a archival/built-in.o archival/libarchive/built-in.o console-tools/built-in.o coreutils/built-in.o coreutils/libcoreutils/built-in.o debianutils/built-in.o klibc-utils/built-in.o e2fsprogs/built-in.o editors/built-in.o findutils/built-in.o init/built-in.o libbb/built-in.o libpwdgrp/built-in.o loginutils/built-in.o mailutils/built-in.o miscutils/built-in.o modutils/built-in.o networking/built-in.o networking/libiproute/built-in.o networking/udhcp/built-in.o printutils/built-in.o procps/built-in.o runit/built-in.o selinux/built-in.o shell/built-in.o sysklogd/built-in.o util-linux/built-in.o util-linux/volume_id/built-in.o -Wl,--end-group -Wl,--start-group -lcrypt -lm -lresolv -Wl,--end-group`
> 
> `/usr/bin/ld: coreutils/lib.a(mktemp.o): in function `mktemp_main':
> mktemp.c:(.text.mktemp_main+0x80): warning: the use of `mktemp' is dangerous, better use `mkstemp' or `mkdtemp' /usr/bin/ld: util-linux/lib.a(rdate.o): in function `rdate_main':
> rdate.c:(.text.rdate_main+0xe4): undefined reference to `stime' /usr/bin/ld: coreutils/lib.a(date.o): in function `date_main':
> date.c:(.text.date_main+0x218): undefined reference to `stime' collect2: error: ld returned 1 exit status Note: if build needs additional libraries, put them in CONFIG_EXTRA_LDLIBS. Example: CONFIG_EXTRA_LDLIBS="pthread dl tirpc audit pam" make[1]: [Makefile:718: busybox_unstripped] Error 1 make[1]: Leaving directory '/home/awlsomealex/Git/minimal/src/work/busybox/busybox-1.31.1' Command exited with non-zero status 2`

https://github.com/ivandavidov/minimal/issues/205#issue-561895600
