### ISSUE TITLE
Failed to recompile all under Ubuntu ...

### ISSUE THREAD

**Issue by JPB1JPB1** [ivandavidov/minimal#207]
Hello
here is the error when it fails to recompile a fresh new version 
""
checking for a BSD-compatible install... /usr/bin/install -c
checking whether ln -s works... yes
checking whether as is GNU as... yes
checking whether ld is GNU ld... yes
checking for as... as
checking version of as... 2.32, ok
checking for ld... ld
checking version of ld... 2.32, ok
checking for gnumake... no
checking for gmake... no
checking for make... make
checking version of make... 4.2.1, ok
checking for gnumsgfmt... no
checking for gmsgfmt... no
checking for msgfmt... msgfmt
checking version of msgfmt... 0.19.8.1, ok
checking for makeinfo... no
checking for sed... sed
checking version of sed... 4.7, ok
checking for gawk... no
checking for bison... bison
checking version of bison... 3.3.2, ok
checking if gcc is sufficient to build libc... yes
checking for nm... nm
checking for python3... python3
checking version of python3... 3.7.3, ok
configure: error: 
*** These critical programs are missing or too old: gawk
*** Check the INSTALL file for required versions.

""

Please, any help to improve the automatic process to compile the great Minimal linux is welcome...

Ubuntu version is
5.0.0-13-generic #14-Ubuntu SMP Mon Apr 15 14:59:14 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

Jp

**Comment by ivandavidov** [comment]
The last two lines provide the answer:

```
*** These critical programs are missing or too old: gawk
*** Check the INSTALL file for required versions.
```

You have to update ``gawk`` and then it should work, unless there are more unsatisfied build dependencies later in the process.

**Comment by JPB1JPB1** [comment]
Hello

Yes, it is solved by using
"
sudo apt-get update -y
sudo apt-get install -y gawk
"
with internet acces for GAWK....
...
Compilation is ok after this manual intervention..
Great Minimal linux
Jp

**Comment by JPB1JPB1** [comment]
Hello

Well , after testing again in a new directory, we get an issue during ./08_prepare_bundles.sh step with an problem around the mini_overlay which was not created or copied...  ?
using the ./build_minimal_linux_live.sh without modification...

We try again, but we haven't seen the ouptut file yet...
On going ...
Best Regards
Jp

**Comment by JPB1JPB1** [comment]
"Fails" to recompile all the step, 
Stop at step ./14xxx due to the package XORRISO under Ubuntu 19.04 is NOT available...
....
For your information..
Any solution to keep going in another way  ? 
Best Regards
Jp

**Comment by ivandavidov** [comment]
I'm using Ubuntu LTS releases. If you are missing some of the build requirements, you are on your own to find them and install them.

You could try to modify the ``14_xx`` script to use whatever ISO image manipulation program you prefer. For instance, you could use ``mkisofs``.

**Comment by JPB1JPB1** [comment]
Ok, thanks, i understand ..

And it helps to do over test for the next build or LTS version if xorriso package is not anymore available... 
Have a good day
Jp
