### ISSUE TITLE
Generate a USB bootable image 

### ISSUE THREAD

**Issue by cirosantilli** [ivandavidov/minimal#21]
It would be great to make it easier for people to run on real hardware if they don't have CDs.

I have implemented it at: https://github.com/cirosantilli/runlinux/blob/8da285b7ddd0f6fa8a411fa020d12bc8f5ee7ef5/runlinux#L82-L84 and could PR here.

I think the image generated by `grub-mkrescue` is also bootable from a CD, but I can't test that (`qemu -cdrom` also works in addition to `-hda`).

@ladiko has also implemented it at https://github.com/ladiko/minimal/blob/0b2ae8b868f1d4294d7d2dfec41b093da5696705/src/create_boot_stick.sh but at 3 lines long I think mine is simpler :-)

**Comment by ladiko** [comment]
my addition directly creates a bootable pen drive, while yours create a bootable image-file which is double the size of the original iso-file. I don't see the benefit.

**Comment by cirosantilli** [comment]
@ladiko cool, I didn't see your method generated much smaller images. A simpler script is a plus though.

**Comment by ladiko** [comment]
My script does not create an image. it installs syslinux to the pen drive's mbr and extracts the kernel and initrd.img from the ISO file to the pen drive. Then the pen drive is bootable with minimal-linux.

**Comment by cirosantilli** [comment]
@ladiko I understand. But it is basically the same no? One could burn (the beginning of) the pendrive to a file or vice versa. I tried a bit with `syslinux` and loop devices but I didn't manage to make the image so easily for some reason.

**Comment by cirosantilli** [comment]
Ah wait, for some reason I was under the impression that the generated `minimal_linux_live.iso` could not boot from a USB, but it actually can! So this issue is useless. Why don't you just burn the ISO to the USB yourself?

**Comment by cirosantilli** [comment]
Ah OK, I finally understand, your method allows one to use the USB as a hard disk. Sorry for so much confusion...
