### ISSUE TITLE
How to eject cd at shutdown

### ISSUE THREAD

**Issue by linus-ha** [ivandavidov/minimal#212]
I want to use MML as an installer, that formats the drive, creates a filesystem and copies some files.
So far so good. But I want to eject the CD at reboot. How could I make this possible? I've doesn't quite get the boot process. 

(Obviously /dev/cd isn't visible/accessible after boot)

**Comment by ivandavidov** [comment]
1. You have to find out what's the boot device. Take a look [here](https://github.com/ivandavidov/minimal/blob/bcc28c2873166b8b81a58d1f1ef034ecefc128e0/src/minimal_rootfs/etc/02_overlay.sh#L67) for a sample code where the ``DEVICE`` variable is the /dev/xxx boot device.

2. Use the ``eject`` command that is available with [Busybox](https://busybox.net/downloads/BusyBox.html). If this command is not available in MLL, then you should enable it in the Busybox configuration before you build the initramfs.
