### ISSUE TITLE
mkfs.ext4 not found (Question)

### ISSUE THREAD

**Issue by theraw** [ivandavidov/minimal#213]
Hello,

Nice project and work, any reason why mkfs.ext4 is not included?

**Comment by ivandavidov** [comment]
This is from the [overview section](https://github.com/ivandavidov/minimal#overview):

_The generated ISO image file contains Linux kernel, GNU C library compiled with default options, **Busybox compiled with default options**, quite simple initramfs structure and some "overlay bundles" (the default build process provides few overlay bundles)._

The userland utilities come from Busybox. You can see for yourself whether ``mkfs.ext4`` exists in Busybox and if so, enable it manually.
