### ISSUE TITLE
How to install new software?

### ISSUE THREAD

**Issue by ee9dc27e41eb201953e1475134e76a26** [ivandavidov/minimal#216]
Maybe this is a stupid question. How do we install new software in MLL? Are we limited to what busybox has to offer? Is there a way to configure APT with MLL?

**Comment by ee9dc27e41eb201953e1475134e76a26** [comment]
Or `bash` for example. I would like to install that. I saw this:

https://github.com/ivandavidov/minimal/issues/122

But I'm not clear on what @bauen1 meant about "bash bundle for self-hosting".

**Comment by TechnologyClassroom** [comment]
There are additional packages in the overlays.  https://github.com/ivandavidov/minimal/tree/master/src/minimal_overlay/bundles

**Comment by ee9dc27e41eb201953e1475134e76a26** [comment]
Thanks, @TechnologyClassroom. So there's no way to install packages outside of the bundles you linked to? Really, I just need Bash.

**Comment by ivandavidov** [comment]
Did you read this section?

https://github.com/ivandavidov/minimal#runtime-software
