### ISSUE TITLE
Provide ISO Releases

### ISSUE THREAD

**Issue by toddjames** [ivandavidov/minimal#218]
Would it be possible to provide releases on this GitHub project with ISO downloads?

I started down the path of minimal Linux on my own, then found this wonderful project when I ran into a little trouble with Busybox. I've followed many parts of the guide, but with a few deviations, such as bootloader and hypervisor. I'm experiencing an issue that I'm trying to narrow down and being able to quickly boot up an ISO from this project to narrow that down further would be helpful. As it stands, I plan to follow the tutorial from start to end to get the final ISO to rule out some variables, but if the ISO was already available, it would be much quicker.

**Comment by ivandavidov** [comment]
You can find all available ISO images on the [Releases](https://github.com/ivandavidov/minimal/releases) page, under the **Assests** section.

**Comment by toddjames** [comment]
Thanks! That's exactly what I was looking for, but I didn't realize that GitHub's layout changed slightly and the Releases page is no longer a tab, but now on the sidebar.
