### ISSUE TITLE
How to add overlay bundles?

### ISSUE THREAD

**Issue by RuslanUC** [ivandavidov/minimal#219]
It is possible to add other overlay bundles?

**Comment by ivandavidov** [comment]
Yes

**Comment by RuslanUC** [comment]
Just build the program with "make install 'path'"?

**Comment by ivandavidov** [comment]
You could try that approach and when it doesn't work, you could try reading
the project documentation.

Simply said - RTFM :)

**Comment by RuslanUC** [comment]
Thanks.
