### ISSUE TITLE
Update the 'crypt' overlay bundle to provide 'libcrypt.so.1' from 'xcrypt'

### ISSUE THREAD

**Issue by ivandavidov** [ivandavidov/minimal#223]
The ``crypt`` library from the GLIBC project is _kind-of-deprecated_ now. The actual shared object library comes from the [xcrypt](https://github.com/besser82/libxcrypt) project. The overlay bundle [glibc_libcrypt](https://github.com/ivandavidov/minimal/blob/master/src/minimal_overlay/bundles/glibc_libcrypt/bundle.sh) has to be updated in order to reflect this change.

Overall instructions

* find proper source for xcrypt
* configure with ``--prefix``
* make + make install
* put the newly produced ``libcrypt.so.1`` shared object library in ``/lib`` as part of the normal overlay bundle build process

Note that the build process from the GitHub sources involves additional tools, e.g. autoconf, automake, etc. which makes the build process a little bit more complicated. That's why the official sources should come from somewhere else.

**Comment by ivandavidov** [comment]
This is quite a simple task (yet very important one), but at the moment I don't have the time to do it properly. Developer assistance is highly appreciated.

**Comment by oxedions** [comment]
Since I am the one asking for it, let me give it a try 🙂

**Comment by oxedions** [comment]
Ok it works 🙂 

Should I rename the bundle from glibc_libcrypt to libxcrypt ?

If yes, how can I manage the fact that glibc_libcrypt seems to be always built when executing bundle main script (08_prepare_bundles.sh) ? Do I force it **on** always, or do it becomes an optional bundle ?

**Comment by oxedions** [comment]
What is the default root password on MLL ? For ssh 😊

**Comment by ivandavidov** [comment]
The root password is set to [toor](https://github.com/ivandavidov/minimal/blob/master/src/minimal_overlay/bundles/dropbear/02_build.sh#L53) in the Dropbear overlay bundle. Otherwise, there is no account and no password at all in MLL and you get a shell prompt with elevated rights just out of the box.

Regarding xcrypt - I don't really mind whether the bundle name is glibc_libcrypt or just libxcrypt (or anything else). I'll leave that judgement to you. Just keep in mind that there are other overlay bundles that depend on libcrypt/xcrypt (starting with [glibc_full](https://github.com/ivandavidov/minimal/blob/master/src/minimal_overlay/bundles/glibc_full/bundle_deps), although it is debatable whether libcrypt should be included or skipped... let's keep it in for now) and no matter how you name the bundle, you'll have to go through the dependencies for each bundle and replace glibc_libcrypt with e.g. libxcrypt. That's not very hard to do (simple copy/paste or with smart 'sed' string replacement) but still, it's a potential issue to have in mind.

Regarding the rebuild script - I designed the build process to always start from scratch and therefore all overlay bundles are going to be rebuilt. The idea is that regardless what goes wrong in the build process, when you run the script again, everything should start from clean slate. This applies for all build scripts, not just this one. However, note that if bundles ``main_a`` and ``main_b`` both depend on bundle ``dep_bundle``, then the latter will be built [only once](https://github.com/ivandavidov/minimal/blob/master/src/minimal_overlay/overlay_build.sh#L66). In particular, no matter how many bundles have dependency on ``libxcrypt``, the bundle which provides the enc/dec library will be built only once.

**Comment by oxedions** [comment]
See #225

**Comment by ivandavidov** [comment]
I'm closing the issue. Thank you for the contribution! :)
