### ISSUE TITLE
/dev/sda mount failed using hdd.img

### ISSUE THREAD

**Issue by iddev5** [ivandavidov/minimal#224]
Mounting of /dev/sda is failing when ran with ``qemu-bios.sh -h``, given that hdd.img is generated with generate_hdd.sh.
```
Device is mounted on /dev/sda
Mounting failed (probably on vfat)
```
I have only made modifications to qemu-bios.sh as it was warning about hdd.img's format not specified:
```
$cmd -drive file=hdd.img,index=0,media=disk,format=raw
```

This issue is only happening when it is ran for the second time. If I regenerate hdd.img then the first time it will work completely fine, but on subsequent runs, it is showing this error.

**Comment by ivandavidov** [comment]
The vfat mount is OK. The failure is related to the overlayfs mount which
doesn't support FAT. You could workaround this issue by uusing ext2/3/4
instead of vfat. Or you could use 'sparse' file for your overlay bundles.

**Comment by iddev5** [comment]
> You could workaround this issue by uusing ext2/3/4 instead of vfat.

Any directions on where to do that?

Additional info: 
1) I m creating hdd.img with ``sudo generate_hdd.sh -f``
2) I have changed nothing in .config except ``USE_LOCAL_SOURCE=true``
3) The error is this: 
![here](https://user-images.githubusercontent.com/54106488/96375683-0d410c00-1198-11eb-91c2-7106f34c0b37.png)

**Comment by ivandavidov** [comment]
My bad - the issue is there, exactly as you have described it. I'll look into it deeper when I have time.

**Comment by ivandavidov** [comment]
One of the overlayfs config options in the kernel is causing issues at runtime. Not sure which one exactly (I have to test them one by one). I have updated all of the overlayfs options with their recommended values (most overlayfs features are now disabled) and the issue is no longer present. I'll update the kernel build source script soon.

**Comment by ivandavidov** [comment]
@iddev5 - the [latest commit](https://github.com/ivandavidov/minimal/commit/8bede67e056eb37204aa44430097df0f38d13c10) should fix the issue. I verified it locally, but still, please let me know if this resolves the issue on your side as well.

Regards,
Ivan Davidov

**Comment by iddev5** [comment]
This commit indeed fixed the issue. It is working fine now on my side!
Thanks for the help :pray:
