### ISSUE TITLE
Bootup process gets stuck at "Run /init as init process" and then QEMU-KVM and even VirtualBox crash after 30 seconds. 

### ISSUE THREAD

**Issue by dragogos-6432** [ivandavidov/minimal#229]
I have tried everything but I couldn't solve the problem.
I have made a single modification where I just replaced the MLL logo with Tux.

**Comment by TechnologyClassroom** [comment]
Do you have the same issue with [these ISOs](https://github.com/ivandavidov/minimal/releases/tag/15-Dec-2019)?

**Comment by ivandavidov** [comment]
I'm closing the issue since it is definitely not related to the core MLL build/runtime process.

@dragogos-6432 - I suggest you try to use MLL without any modifications and then apply your changes one by one. If you still have issues, feel free to raise them.
