### ISSUE TITLE
What would one need to do to use GNU instead of Busybox?

### ISSUE THREAD

**Issue by Nvreformat** [ivandavidov/minimal#24]

**Comment by ivandavidov** [comment]
You would need GNU core utils:

http://www.gnu.org/software/coreutils/coreutils.html

I'm researching the option "glibc + coreutils" and most probably I'll drop the "musl + BusyBox" approach due to multiple headers incompatibility between musl and the kernel.

**Comment by ivandavidov** [comment]
The latest published stable release '03-Apr-2016' uses glibc and BusyBox. Using GNU packages is not an issue at the moment.
