### ISSUE TITLE
Fails to build on Ubuntu 20.04.2 LTS

### ISSUE THREAD

**Issue by Tristi-X** [ivandavidov/minimal#242]
So I just followed the steps to build on my Ubuntu system but it suddenly fails.
Here are the last lines of the terminal output:
```
[...]
linux-5.11.10/virt/kvm/eventfd.c
linux-5.11.10/virt/kvm/irqchip.c
linux-5.11.10/virt/kvm/kvm_main.c
linux-5.11.10/virt/kvm/vfio.c
linux-5.11.10/virt/kvm/vfio.h
linux-5.11.10/virt/lib/
linux-5.11.10/virt/lib/Kconfig
linux-5.11.10/virt/lib/Makefile
linux-5.11.10/virt/lib/irqbypass.c
tar: Exiting with failure status due to previous errors
```

**Comment by ivandavidov** [comment]
Well, if you read the last line of the output, you should notice there are more errors somewhere above. Please, find the error and analyze it. My guess is that you're either out of disk space, or the downloaded archive is corrupted for some reason.

**Comment by Tristi-X** [comment]
I couldn't find any other errors but it seems like I didn't have enough storage even though there were like 5G left and the folder i was working in was on another drive.
However, it works now so thank you very much
