### ISSUE TITLE
pulling in bundles from web...live

### ISSUE THREAD

**Issue by mrgreen3** [ivandavidov/minimal#247]
Messing around with ML iso, saw README with guide on how to add bundles. Wanting to test more before rebuilding iso again...

Is it possible to pull in bundles via web live? can see wget is in busybox... would very much like to add things like tmux or htop, space invaders ;-)

**Comment by ivandavidov** [comment]
MLL allows you to add `static-get` as an overlay bundle. You can use it to download additional stuff/programs while MLL is running.
