### ISSUE TITLE
Add Openssl

### ISSUE THREAD

**Issue by jtloper1** [ivandavidov/minimal#25]
For my application I want to run folding at home version 7. In order to download the client I need openssl. I think I see how this kind of thing works from looking at the musl-busybox scripts. Is that a good example of what would need to be done?

**Comment by ivandavidov** [comment]
There is only one way to know - try it. :)

FYI - you can also check the experimental folder 'glibc-busybox' which solves the DNS issue in different way. The network functionality works fine on 32bit machines but the downside is that the build now is considerably bigger (and not minimal at all) and it takes more RAM to load (~256 MB).
