### ISSUE TITLE
How to disable or run on background all slow IO boot operations?

### ISSUE THREAD

**Issue by cirosantilli** [ivandavidov/minimal#33]
I'm talking about two types of things:

- press space or wait some seconds actions. We could either have an option of config file to:
     - choose an option and ask nothing
     - disable them and take a fixed default if the above is not technically possible
- network discovery startup: possible run on background? Buildroot 2016.05 `qemu_x86_64_defconfig` does it.

Those would speed up the boot process and make it more automatic.

BTW, those features are awesome... I just wish boot was faster :-)

**Comment by ivandavidov** [comment]
Regarding bullet point 1 - feel free to research & implement it in your own clone of MLL. You can always provide default (hard coded) screen resolution and you can always provide shorter read timeout for the rescue shells (or disable this functionality completely). None of this is configurable now but it can be easily achieved.

Regarding the network - please refer to the **dhcpd** documentation and see for yourself how you can run it in background.

**Comment by ivandavidov** [comment]
I'm closing the issue - feel free to implement all of these suggestions in your fork of MLL.
