### ISSUE TITLE
User Login?

### ISSUE THREAD

**Issue by AwlsomeAlex** [ivandavidov/minimal#43]
With the addition of Minimal Linux Live being Installable to other machines, would it be possible to create another user in the Installation Progress? Or even better, provide a login prompt for the root user? I tired looking around in the init (since that is where it would most likely be added) but I can't seem to find `/sbin/init`, which is executed after OverlayFS has been added. What file is being copied over into the OverlayFS to become `/sbin/init`?

**Comment by ivandavidov** [comment]
``/sbin/init`` is invoked from ``/etc/03_init.sh``. Take a look at the source here:

https://github.com/ivandavidov/minimal/blob/master/src/minimal_rootfs/etc/03_init.sh

The ``/sbin/init`` command is part of BusyBox and it comes as part of the initramfs. Therefore, you won't find it in the overlay structure unless you manually put there another binary with the same name.

Adding another user is quite simple. I have already described the process in the document ``The DAO of Minimal Linux Live``.

https://github.com/ivandavidov/minimal/blob/master/src/the_dao_of_minimal_linux_live.txt

I have already implemented the process in the ``Dropbear SSH`` overlay bundle, where the ``root`` user is created as part of the overlay structure.

https://github.com/ivandavidov/minimal/blob/master/src/overlay_dropbear_02_build.sh

Currently the installer is very basic and it works only in BIOS mode. I have recently added UEFI boot support but the actual installer needs further improvement in this area. Feel free to update the installer and add whatever stuff you need there.

Cheers!

**Comment by AwlsomeAlex** [comment]
Okay, thanks! Did some research, it's something that has to be done in the /etc/inittab file.
