### ISSUE TITLE
DNS queries are not working in busybox

### ISSUE THREAD

**Issue by andmaj** [ivandavidov/minimal#5]
DNS queries are not working in busybox.

Description of the problem:
1. /etc/resolv.conf is populated with name servers
2. Route to name server is set (checked with ping)
3. nslookup/ping fails for any domain (but the name server address is correct in nslookup)

Possible cause:
Statically-linked glibc programs (like busybox in this case) can't use getaddrinfo / gethostbyname functions without providing a libnss library (which is dynamically loaded).

**Comment by eterps** [comment]
> I have considered some additional features (e.g. networking, desktop, package manager) but the more I think about these features, the more I realize I'm getting closer to the Linux From Scratch project which is not minimal at all.

What would make it 'minimal' in my opinion is if the set of .sh scripts could be extended with additional readable shell scripts to get to these features. Which is a very different goal than the Linux From Scratch project.

**Comment by ivandavidov** [comment]
The issue has been resolved completely in the latest published version.

**Comment by andmaj** [comment]
It's great news! I will give it another try.
