### ISSUE TITLE
cannot boot image using QEmu

### ISSUE THREAD

**Issue by DxCx** [ivandavidov/minimal#62]
Hey,

I've built my own image, then tried to run it using QEmu. QEmu just stuck with no output.
then i tried to pull the offical images from website, both 32 and 64 edition does the same.

P.S:
Im running macOS Sierra

**Comment by ivandavidov** [comment]
It's a local issue, most probably related to the amount of RAM required by the qemu binaries. The official images work fine. If you are able to run MLL via the [website](http://minimal.idzona.com/emulator/), you should be able to run it via qemu as well. I suggest you try to increase the RAM for qemu and then try to run MLL again.

As a general guide - you could also try running MLL via VirtualBox or VMware Player.

**Comment by DxCx** [comment]
yeah, on virtualBox the image is loaded.
but on qemu it does not, the wired thing is that i've run test image for qemu from a blog post i've found and it seemed to be working.. :S

**Comment by ivandavidov** [comment]
In this case I consider the issue as kind-of-resolved. The fact that you are able to run MLL via VirtualBox suggests that there is nothing broken with MLL and you have already configured proper VM engine for your future tests.

**Comment by bauen1** [comment]
For further help, It would be interesting to see the command you used to run qemu with the image

**Comment by DxCx** [comment]
yeah, but QEMU does pass the test image provided with it, so i cannot really blame QEMU as well..
tought maybe somone already seen this kind of behavior before but if you think MLL is perfectly fine, then you can close the issue.
@bauen1 - sry im not home, but the same exact one in qemu64.sh (without hdd)

**Comment by ivandavidov** [comment]
The qemu helper scripts are just helper scripts. As I said, you might need to adjust the RAM settings there and/or other qemu settings specific for your machine/OS. The same scripts work fine on Ubuntu/Mint on x86/x64 CPU architectures.

**Comment by ivandavidov** [comment]
I'm closing the issue.
