### ISSUE TITLE
Linux Kernel 4.10 =< Unfinished Configuration

### ISSUE THREAD

**Issue by AwlsomeAlex** [ivandavidov/minimal#72]
In Linux Kernel 4.10, they added more EFI support (specifically towards Apple Devices) to the configuration. However they failed to introduce a default value so whenever the `02_build_kernel.sh` script is executed it hangs at the configuration section below:
[APPLE_PROPERTIES](http://i.imgur.com/FMAhHc0.png)
I've tried to create a `sed` to set a default value in the configuration but this specific setting is only found in a Kconfig table in the directory `drivers/firmware/efi/Kconfig`. An easy fix would to just say "Use Linux Kernel 4.9 and below!" or "Input 'n' manually." but I just wanted to bring this to your attention to see if you have any suggestions on automating this.

Theres also another one for [OVERLAY_FS_REDIRECT_DIR](http://imgur.com/0XAVDWhl.png) but I haven't tested to see if adding a 'sed' command for the default config would work.

**Comment by AwlsomeAlex** [comment]
Nevermind turns out it wasn't asking because it didn't exist in the .config! I will send a PR that'll add those default configuration values if the Kernel Version is greater than 4.9

**Comment by AwlsomeAlex** [comment]
#73

**Comment by ivandavidov** [comment]
Thank you for the suggested improvement. I haven't tested kernel 4.10 but I currently see no harm in allowing these particular improvements.

**Comment by ivandavidov** [comment]
FYI - you can read more about the ``OVERLAY_FS_REDIRECT_DIR`` in the **renaming directories** section [here](https://www.kernel.org/doc/Documentation/filesystems/overlayfs.txt).
