### ISSUE TITLE
All source based overlay bundles are broken on Ubuntu 16.04

### ISSUE THREAD

**Issue by ivandavidov** [ivandavidov/minimal#81]
I have tested manually all overlay bundles with the latest changes on Ububtu 16.04. Unfortunately they all seem to be broken due to some GCC issues with the recently introduced ``-specs`` functionality. Going back to older kernel and glibc is not an option (the project moves ahead).

**Comment by ivandavidov** [comment]
I have removed the ``-specs`` functionality (at least temporarily) in order to have stable overlay builds.

**Comment by bauen1** [comment]
I will try to look into this, as soon as I can.

If possible, could you provide the Output of  compiling nweb with '--verbose' passed to gcc ?
> Am 05.08.2017 um 12:29 schrieb Ivan Davidov <notifications@github.com>:
> 
> builds.

**Comment by ivandavidov** [comment]
@bauen1 - you can find the requested information here:

https://gist.github.com/ivandavidov/bb3aaa053f8886b53bb3c18e4d7183ed

I like your idea and it is really good. However, both on Mint and Ubuntu the provided ``--specs`` approach doesn't work out of the box. This solution may have worked for you but I'm sure that since I had troubles with it, many other MLL users will experience the same issues. This is why I'd rather revert to the older state (for now) until there is permanent and fully tested solution.

**Comment by ivandavidov** [comment]
I'm closing this issue since the overlay bundle build process is stable for now. The idea behind the proposed ``--specs`` feature is great and I am willing to adopt it in the future if it is stable enough.
