### ISSUE TITLE
Add startup script for the SSH server

### ISSUE THREAD

**Issue by ivandavidov** [ivandavidov/minimal#82]
The currently existing ``dropbear`` overlay bundle needs additional autorun script which properly handles the start process of the SSH server. Hints regarding the startup process can be found [here](https://github.com/ivandavidov/minimal/blob/master/src/README). Note that these explanations have been provided for interactive console and the actual autorun process has to be slightly different.

**Comment by AwlsomeAlex** [comment]
I created a script for StarLinux (starinit) that appears to work if you want to fork it. May need some minor adjusting but go nuts. [Dropbear Init - starinit](https://github.com/AwlsomeAlex/starinit/blob/master/src/etc/init.d/S99dropbear)

**Comment by alex9099** [comment]
Is this already implemented on the builds?

**Comment by ivandavidov** [comment]
@alex9099 - this feature hasn't been implemented yet. However, the SSH server can be started manually without any issues.
